language: node_js
node_js:
  - "12.16"
install:
  - npm install react
  - npm install -g react-scripts
  - npm install -g firebase-tools
script:
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN