language: node_js
node_js:
  - "stable"
# install:
#   - npm install react
#   - npm install -g react-scripts
#   - npm install -g firebase-tools
script:
  - npm run build
# deploy:
#   provider: firebase
#   token:
#     secure: ""
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
on:
  branch: master