language: node_js
node_js:
  - "stable"
# install:
#   - npm install react
#   - npm install -g react-scripts
#   - npm install -g firebase-tools
script:
  - npm run build
deploy:
  provider: firebase
  token:
    secure: "1//03oM-wlg8wjxSCgYIARAAGAMSNwF-L9IrLp7sXwnHars74vlj8C55hvvgwswe16-yjlUt5zy75VH8oFt8SWUveKeRxVitdwFV_sc"
# after_success:
#   - firebase deploy --token $FIREBASE_TOKEN
on:
  branch: master